# Generated by Django 4.0.6 on 2022-08-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_perecent_result_percent_alter_result_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
