# Generated by Django 4.0.6 on 2022-08-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_id',
        ),
    ]
